### ISSUE TITLE
Create ToDo

### ISSUE THREAD

**Issue by mangealonso** [mangealonso/xUnitTests#2]
- [x] Return ToDo information with the same values
- [x] Create RED test return ToDo information with the same values
- [x] Retest and refactor return ToDo information with the same values
- [x] Handle ToDo if null
- [x] Create RED test handle ToDo if null
- [x] Retest and handle ToDo if null
- [x] Return success flag on result
