### ISSUE TITLE
Delete Todo

### ISSUE THREAD

**Issue by mangealonso** [mangealonso/xUnitTests#4]
- [x] Confirm ToDo delete
- [x] Create RED test confirm ToDo delete
- [x] Retest and refactor confirm ToDo delete
- [x] Return list after ToDo delete
- [x] Create RED test return list after ToDo delete
- [x] Retest and refactor return list after ToDo delete
- [x] Handle ToDo delete if null
- [x] Create RED test handle ToDo delete if null
- [x] Retest and handle ToDo delete if null
- [x] Return success flag on result
